# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passsword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
